HOST_IP: 10.100.0.138
IMG: E:\upgrade.img.enc
PASSWORD: user
USERNAME: user
TEMPLATE: ======================.yaml
MAC: 00:B8:C2:95:9F:BD
SN : '777777777777'
WAN_GATEWAY_IPOE: 10.8.8.1
WAN_GATEWAY_PPPOE: 192.168.10.1
PC_LAN_INTF_NAME: '以太网 2'
STATIC_IP_IF_NO_DHCP: 10.100.0.1
PC_PPPOE_NAME: '宽带连接'
WAN_INTF: 'eth4'
VLAN_PPPOE: ''
VLAN_IPOE: ''
VLAN_BRIDGE: ''
PPPUSERNAME: 'user1'
PPPPASSWORD: 'user1'
PC_WIFI_INTF_NAME: 'WLAN'
WIFI_PREFIX: 'WIFI'